# =============================================================================
# Plot the RGM v2.0 examples (channel/canyon/drainage unconformities and
# karst cave systems) generated by x_generate_unconf_channel and
# x_generate_karst, using pymplot's x_showmatrix/x_showslice.
# =============================================================================

# 3D dimensions of the v2.0 examples
n1 = 151
n2 = 201
n3 = 251

# 2D dimensions
m1 = 151
m2 = 301

opts3 = " -n1=#{n1} -n2=#{n2} -n3=#{n3} -legend=y \
    -label1='Depth (grid number)' -label2='X2 (grid number)' -label3='X3 (grid number)' "

opts2 = " -n1=#{m1} -n2=#{m2} -legend=y \
    -label1='Depth (grid number)' -label2='X2 (grid number)' "


# =============================================================================
# Channel/canyon/drainage unconformities

slice = " -slice1=50 -slice2=100 -slice3=125 "

for shape in ['meander_channel', 'meander_canyon', 'drainage_channel', 'drainage_canyon']

    # 3D velocity with the unconformity: slices through the incised surface
    system "x_showslice -in=example_3d_vp_unconf_#{shape}_151x201x251.bin \
        #{opts3} #{slice} -color=jet -unit='Vp (m/s)' \
        -out=example_3d_vp_unconf_#{shape}.png &"

    # 3D image
    system "x_showslice -in=example_3d_image_unconf_#{shape}_151x201x251.bin \
        #{opts3} #{slice} -color=binary -unit='Amplitude' \
        -out=example_3d_image_unconf_#{shape}.png &"

    # 2D velocity section
    system "x_showmatrix -in=example_2d_vp_unconf_#{shape}_151x301.bin \
        #{opts2} -color=jet -unit='Vp (m/s)' \
        -out=example_2d_vp_unconf_#{shape}.png &"

    # 2D image
    system "x_showmatrix -in=example_2d_image_unconf_#{shape}_151x301.bin \
        #{opts2} -color=binary -unit='Amplitude' \
        -out=example_2d_image_unconf_#{shape}.png &"

end

# Two channel unconformities + salt
system "x_showslice -in=example_3d_vp_unconf_channel_salt_151x201x251.bin \
    #{opts3} #{slice} -color=jet -unit='Vp (m/s)' \
    -out=example_3d_vp_unconf_channel_salt.png &"


# =============================================================================
# Karst

slice = " -slice1=100 -slice2=100 -slice3=125 "

# 3D karst: velocity
# 1 = karst caves only; 2 = karst + salt + channel unconformity (elastic)
for i in 1..2

    system "x_showslice -in=example_3d_vp_karst_#{i}_151x201x251.bin \
        #{opts3} #{slice} -color=jet -unit='Vp (m/s)' \
        -out=example_3d_vp_karst_#{i}.png &"

end

# 3D karst mask overlay on the image
system "x_showslice -in=example_3d_karst_1_151x201x251.bin -background=example_3d_image_karst_1_151x201x251.bin \
    #{opts3} #{slice} -color=jet -backcolor=gray -alphas=0:0,0.49:0,0.5:1 -unit='Karst' \
    -out=example_3d_karst_mask_1.png &"

# 2D karst: velocity and image
for i in 1..2

    system "x_showmatrix -in=example_2d_vp_karst_#{i}_151x301.bin \
        #{opts2} -color=jet -unit='Vp (m/s)' \
        -out=example_2d_vp_karst_#{i}.png &"

end

system "x_showmatrix -in=example_2d_image_karst_1_151x301.bin \
    #{opts2} -color=binary -unit='Amplitude' \
    -out=example_2d_image_karst_1.png &"
