# =============================================================================
# Plot the strike-varying fault examples generated by x_generate_curved_3d
# (the "Strike-varying faults" and "Strike-varying faults with spatially
# varying displacement" blocks in example_rgm3_curved.f90) using pymplot's
# x_showslice.
# =============================================================================

n1 = 171
n2 = 251
n3 = 251

opts = " -n1=#{n1} -n2=#{n2} -n3=#{n3} -slice1=40 -slice2=125 -slice3=125 \
    -color=jet -legend=y \
    -label1='Depth (grid number)' -label2='X2 (grid number)' -label3='X3 (grid number)' "

# Fault attributes overlaid on the seismic image
fopts = opts + " -backcolor=gray "


# =============================================================================
# Seismic image with strike-varying faults, colored by the local strike/dip angle

system "x_showslice -in=example_3d_fstrike_vstrike_1.bin -background=example_3d_image_vstrike_1.bin \
    #{fopts} -alphas=0:0,0.9:0,1:1 -unit='Fault strike (degree)' \
    -out=example_3d_fstrike_vstrike_1.png &"

system "x_showslice -in=example_3d_fdip_vstrike_1.bin -background=example_3d_image_vstrike_1.bin \
    #{fopts} -alphas=0:0,0.9:0,1:1 -unit='Fault dip (degree)' \
    -out=example_3d_fdip_vstrike_1.png &"


# =============================================================================
# Seismic image with faults of spatially varying displacement, colored by the
# local displacement; the displacement is maximum at the slip patch center and
# diminishes toward the fault tip lines. The decay case additionally has the
# displacement decaying away from the faults (fault drag / rollover /
# blind-fault folding)

for tag in ['vdisp_1', 'vdisp_decay_1']

    system "x_showslice -in=example_3d_fdisp_#{tag}.bin -background=example_3d_image_#{tag}.bin \
        #{fopts} -alphas=0:0,0.49:0,0.5:1 -unit='Fault displacement (grid number)' \
        -out=example_3d_fdisp_#{tag}.png &"

end


# =============================================================================
# Velocity models: strike-varying faults; spatially varying displacement;
# and spatially varying displacement with decay (drag/rollover in the model)

for tag in ['vstrike_1', 'vdisp_1', 'vdisp_decay_1']

    system "x_showslice -in=example_3d_vp_#{tag}.bin #{opts} -unit='Vp (m/s)' \
        -out=example_3d_vp_#{tag}.png &"

end
