[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "rgm"
version = "2.0.0"
description = "Python interface to RGM: random geological model generation for machine learning"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["numpy"]

[tool.setuptools]
packages = ["rgm"]
