!
! © 2024-2026. Triad National Security, LLC. All rights reserved.
!
! This program was produced under U.S. Government contract 89233218CNA000001
! for Los Alamos National Laboratory (LANL), which is operated by
! Triad National Security, LLC for the U.S. Department of Energy/National Nuclear
! Security Administration. All rights in the program are reserved by
! Triad National Security, LLC, and the U.S. Department of Energy/National
! Nuclear Security Administration. The Government is granted for itself and
! others acting on its behalf a nonexclusive, paid-up, irrevocable worldwide
! license in this material to reproduce, prepare derivative works,
! distribute copies to the public, perform publicly and display publicly,
! and to permit others to do so.
!
! Author:
!    Kai Gao, kaigao@lanl.gov
!

!==============================================================================
! Synthetic karst cave structure generator
!
! Algorithm — Ornstein-Uhlenbeck tube network
! --------------------------------------------
! 1. Passage geometry: each of the n_passages cave conduits is represented by
!    n_ctrl control points in 3-D grid-cell coordinates.  The first control
!    point is placed either at a random location (probability 1 − p_connect)
!    or at an endpoint of an already-generated passage (probability p_connect),
!    producing a connected, tree-like network when p_connect → 1.
!
! 2. Ornstein-Uhlenbeck walk: successive control points are generated by a
!    discrete OU process for the unit direction vector d:
!      d_new = phi · d_old + (1 − phi) · noise/|noise|,   phi = 1 − tortuosity
!    The result is then renormalised.  phi = 1 → perfectly straight passage;
!    phi = 0 → uncorrelated random walk (maximally tortuous).
!    Step length between control points is fixed at 2 · r_mean.
!    Domain boundaries are treated as reflectors (direction component flips).
!
! 3. Radii: each control point is assigned a tube radius drawn from
!      r = max(0.5, r_mean · (1 + r_std · N(0,1)))
!    Interior radii are further smoothed by a 3-point running average.
!
! 4. Rasterisation: for each consecutive pair of control points the tube is
!    a tapered capsule (radius linearly interpolated from ra to rb).  The
!    signed distance from a voxel centre to the capsule axis is computed
!    analytically (tube3 SDF); any voxel with sd ≤ 0 is marked as cave void.
!
! 5. Caprock: passage generation is confined to iz = 1 … nint(z_top · nz),
!    keeping the uppermost (1 − z_top) fraction of the grid as solid rock.
!
! Public OOP API
! --------------
!   type(karst_2d) :: k
!   grid = k%generate()    ! real(sp)(nx,nz): vertical x-z cross-section
!                          ! 1.0 = cave void, 0.0 = host rock
!
!   type(karst_3d) :: k3
!   vol = k3%generate()    ! real(sp)(nx,ny,nz): full 3-D cave volume
!                          ! 1.0 = cave void, 0.0 = host rock
!
! Typical parameters on a 128-cell grid:
!   n_passages=15, n_ctrl=40, r_mean=4.0, r_std=0.35, tortuosity=0.6, p_connect=0.7
!==============================================================================

module geological_model_karst

    use libflit
    use geological_model_utility
    use, intrinsic :: iso_fortran_env, only: dp => real64, sp => real32
    implicit none
    private

    !> Vertical x-z cross-section through a 3-D karst cave model.
    !> Internally generates a 3-D volume with ny = 1 and returns the single y-slice,
    !> giving a genuine vertical cross-section with cave voids in the x-z plane.
    !> generate() returns real(sp)(nz,nx) with the model top at index 1 of
    !> the first (depth) dimension: 1.0 = cave void, 0.0 = host rock.
    type karst_2d
        integer  :: nx = 128          ! horizontal cells (x-axis of the output slice)
        integer  :: nz = 64           ! vertical cells   (z-axis; iz=1 = deepest)
        integer  :: n_passages = 15   ! number of cave passages to generate
        integer  :: n_ctrl = 40       ! OU control points per passage (more → longer/more complex passages)
        real(dp) :: r_mean = 4.0_dp   ! mean tube radius in grid cells
        real(dp) :: r_std = 0.35_dp   ! fractional std dev of radius along passage (connected passages use 0.4*r_std)
        real(dp) :: tortuosity = 0.6_dp ! sinuosity of passages: 0 = straight, 1 = fully random walk
        real(dp) :: p_connect = 0.7_dp  ! probability a new passage starts at an existing endpoint (0=isolated, 1=tree)
        integer  :: seed = -1         ! random seed
        real(dp) :: z_top = 0.85_dp   ! caprock fraction: passages confined to iz = 1..nint(z_top·nz)
    contains
        procedure :: generate => generate_karst_xz
    end type karst_2d

    !> Full 3-D karst cave volume.
    !> generate() returns real(sp)(nz,ny,nx) with the model top at index 1 of
    !> the first (depth) dimension: 1.0 = cave void, 0.0 = host rock.
    type karst_3d
        integer  :: nx = 128, ny = 128, nz = 64  ! output grid dimensions
        integer  :: n_passages = 15   ! number of cave passages
        integer  :: n_ctrl = 40       ! OU control points per passage
        real(dp) :: r_mean = 4.0_dp   ! mean tube radius in grid cells
        real(dp) :: r_std = 0.35_dp   ! fractional std dev of radius along passage (connected passages use 0.4*r_std)
        real(dp) :: tortuosity = 0.6_dp ! sinuosity: 0 = straight, 1 = random walk
        real(dp) :: p_connect = 0.7_dp  ! branching probability (0=isolated, 1=connected tree)
        integer  :: seed = -1         ! random seed
        real(dp) :: z_top = 0.85_dp   ! caprock fraction: passages stay below nint(z_top·nz)
    contains
        procedure :: generate => generate_karst_3d
    end type karst_3d

    public :: karst_2d
    public :: karst_3d

contains

    ! ── signed distance: point → tapered tube segment ─────────────────────────
    ! Negative value means the point is inside the tube.
    ! Radius linearly interpolates from ra (at a) to rb (at b).

    pure function tube3(px, py, pz, ax, ay, az, bx, by, bz, ra, rb) result(sd)
        real(dp), intent(in) :: px, py, pz, ax, ay, az, bx, by, bz, ra, rb
        real(dp) :: sd, t, ex, ey, ez, len2
        ex = bx - ax
        ey = by - ay
        ez = bz - az
        len2 = ex*ex + ey*ey + ez*ez
        if (len2 < 1.0e-20_dp) then
            t = 0.0_dp
        else
            t = max(0.0_dp, min(1.0_dp, ((px - ax)*ex + (py - ay)*ey + (pz - az)*ez)/len2))
        end if
        sd = hypot(hypot(px - ax - t*ex, py - ay - t*ey), pz - az - t*ez) - (ra + t*(rb - ra))
    end function tube3

    ! ── passage generation ────────────────────────────────────────────────────
    ! ndim = 3.  pts(ndim, n_ctrl, n_passages), radii(n_ctrl, n_passages).
    ! Control points are in grid-cell coordinates (1-based).

    subroutine make_passages(ndim, nx, ny, nz, n_passages, n_ctrl, &
            r_mean, r_std, tortuosity, p_connect, seed, &
            pts, radii)
        integer, intent(in)  :: ndim, nx, ny, nz, n_passages, n_ctrl, seed
        real(dp), intent(in)  :: r_mean, r_std, tortuosity, p_connect
        real(dp), allocatable, intent(out) :: pts(:, :, :)   ! (ndim, n_ctrl, n_passages)
        real(dp), allocatable, intent(out) :: radii(:, :)   ! (n_ctrl, n_passages)

        real(dp), allocatable :: rn_dir(:), rn_rad(:), rn_pos(:), rn_con(:)
        real(dp), allocatable :: node_pool(:, :)
        real(dp) :: dx(3), dlen, phi, step, lx(3), zlo, wl, r_std_eff
        integer  :: ip, ic, k, n_nodes, i_node
        logical  :: connected

        phi = 1.0_dp - tortuosity
        step = 2.0_dp*r_mean

        lx(1) = real(nx, dp)
        lx(2) = real(ny, dp)
        lx(3) = merge(real(nz, dp), 1.0_dp, ndim == 3)

        ! Keep passage centerlines at least one (typical maximum) tube radius
        ! above the deepest boundary, so that caves taper naturally instead of
        ! being chopped flat at the bottom of the karst zone
        zlo = 1.0_dp + r_mean*(1.0_dp + 2.0_dp*r_std)
        zlo = min(zlo, 1.0_dp + 0.3_dp*lx(3))

        allocate (pts(ndim, n_ctrl, n_passages))
        allocate (radii(n_ctrl, n_passages))
        allocate (node_pool(ndim, 2*n_passages))
        n_nodes = 0

        do ip = 1, n_passages

            rn_dir = random(3*n_ctrl, dist='normal', seed=ifelse(seed == -1, -1, safe_seed(int(seed, 8)*11 + ip*17)))
            rn_rad = random(n_ctrl, dist='normal', seed=ifelse(seed == -1, -1, safe_seed(int(seed, 8)*13 + ip*19)))
            rn_pos = random(3, dist='uniform', seed=ifelse(seed == -1, -1, safe_seed(int(seed, 8)*7 + ip*23)))
            rn_con = random(2, dist='uniform', seed=ifelse(seed == -1, -1, safe_seed(int(seed, 8)*5 + ip*29)))

            if (n_nodes > 0 .and. rn_con(1) < p_connect) then
                i_node = min(n_nodes, max(1, int(rn_con(2)*n_nodes) + 1))
                pts(:, 1, ip) = node_pool(:, i_node)
                connected = .true.
            else
                do k = 1, ndim
                    pts(k, 1, ip) = 1.5_dp + rn_pos(k)*(lx(k) - 2.0_dp)
                end do
                if (ndim == 3) then
                    pts(3, 1, ip) = zlo + rn_pos(3)*max(lx(3) - zlo - 1.0_dp, 0.0_dp)
                end if
                connected = .false.
            end if

            ! Connected passages use a reduced radius variation so that
            ! multi-passage cave systems read as relatively smooth tubes;
            ! isolated passages keep the full variation and may be beaded
            if (connected) then
                r_std_eff = 0.4_dp*r_std
            else
                r_std_eff = r_std
            end if

            dlen = max(sqrt(rn_dir(1)**2 + rn_dir(2)**2 + rn_dir(3)**2), 1.0e-10_dp)
            dx(1) = rn_dir(1)/dlen
            dx(2) = rn_dir(2)/dlen
            dx(3) = rn_dir(3)/dlen

            radii(1, ip) = max(0.5_dp, r_mean*(1.0_dp + r_std_eff*rn_rad(1)))

            do ic = 2, n_ctrl
                dlen = max(sqrt(rn_dir(3*(ic - 1) + 1)**2 + &
                    rn_dir(3*(ic - 1) + 2)**2 + &
                    rn_dir(3*(ic - 1) + 3)**2), 1.0e-10_dp)
                do k = 1, 3
                    dx(k) = phi*dx(k) + (1.0_dp - phi)*rn_dir(3*(ic - 1) + k)/dlen
                end do
                dlen = max(sqrt(dx(1)**2 + dx(2)**2 + dx(3)**2), 1.0e-10_dp)
                dx = dx/dlen

                do k = 1, ndim
                    wl = 1.0_dp
                    if (k == 3) then
                        wl = zlo
                    end if
                    pts(k, ic, ip) = pts(k, ic - 1, ip) + dx(k)*step
                    if (pts(k, ic, ip) < wl) then
                        pts(k, ic, ip) = 2.0_dp*wl - pts(k, ic, ip)
                        dx(k) = -dx(k)
                    else if (pts(k, ic, ip) > lx(k)) then
                        pts(k, ic, ip) = 2.0_dp*lx(k) - pts(k, ic, ip)
                        dx(k) = -dx(k)
                    end if
                end do
                dlen = max(sqrt(dx(1)**2 + dx(2)**2 + dx(3)**2), 1.0e-10_dp)
                dx = dx/dlen
                radii(ic, ip) = max(0.5_dp, r_mean*(1.0_dp + r_std_eff*rn_rad(ic)))
            end do

            do ic = 2, n_ctrl - 1
                radii(ic, ip) = (radii(ic - 1, ip) + radii(ic, ip) + radii(ic + 1, ip))/3.0_dp
            end do

            n_nodes = n_nodes + 1
            node_pool(:, n_nodes) = pts(:, 1, ip)
            n_nodes = n_nodes + 1
            node_pool(:, n_nodes) = pts(:, n_ctrl, ip)
        end do

    end subroutine make_passages

    ! ── 3-D karst volume (internal) ───────────────────────────────────────────

    subroutine karst_volume(nx, ny, nz, vol, n_passages, n_ctrl, &
            r_mean, r_std, tortuosity, p_connect, seed, z_top)
        integer, intent(in)  :: nx, ny, nz, n_passages, n_ctrl, seed
        real(dp), intent(in), optional :: z_top
        real(sp), allocatable, intent(out) :: vol(:, :, :)
        real(dp), intent(in)  :: r_mean, r_std, tortuosity, p_connect

        real(dp), allocatable :: pts(:, :, :), radii(:, :)
        real(dp) :: px, py, pz, r_max
        real(dp) :: ax, ay, az, bx, by, bz, ra, rb
        integer  :: ip, ic, ix, iy, iz, ix0, ix1, iy0, iy1, iz0, iz1, nz_eff

        nz_eff = nz
        if (present(z_top)) then
            nz_eff = min(nz, max(1, nint(z_top*nz)))
        end if

        call make_passages(3, nx, ny, nz_eff, n_passages, n_ctrl, &
            r_mean, r_std, tortuosity, p_connect, seed, &
            pts, radii)

        allocate (vol(nx, ny, nz))
        vol = 0.0_sp

        do ip = 1, n_passages
            do ic = 1, n_ctrl - 1
                ax = pts(1, ic, ip)
                ay = pts(2, ic, ip)
                az = pts(3, ic, ip)
                bx = pts(1, ic + 1, ip)
                by = pts(2, ic + 1, ip)
                bz = pts(3, ic + 1, ip)
                ra = radii(ic, ip)
                rb = radii(ic + 1, ip)
                r_max = max(ra, rb) + 0.5_dp

                ix0 = max(1, int(min(ax, bx) - r_max))
                ix1 = min(nx, int(max(ax, bx) + r_max) + 1)
                iy0 = max(1, int(min(ay, by) - r_max))
                iy1 = min(ny, int(max(ay, by) + r_max) + 1)
                iz0 = max(1, int(min(az, bz) - r_max))
                iz1 = min(nz, int(max(az, bz) + r_max) + 1)

                do iz = iz0, iz1
                    pz = real(iz, dp)
                    do iy = iy0, iy1
                        py = real(iy, dp)
                        do ix = ix0, ix1
                            px = real(ix, dp)
                            if (tube3(px, py, pz, ax, ay, az, bx, by, bz, ra, rb) <= 0.0_dp) then
                                vol(ix, iy, iz) = 1.0_sp
                            end if
                        end do
                    end do
                end do
            end do
        end do

    end subroutine karst_volume

    ! ── OOP generate functions ────────────────────────────────────────────────

    !> Generate a vertical x-z cross-section through a 3-D karst model.
    !> Returns real(sp)(nz,nx), top at index 1: 1.0 = cave void, 0.0 = host rock.
    !> The third dimension (y) is collapsed to ny=1, so all passages
    !> develop in the x-z plane giving genuine cave cross-section geometry.
    function generate_karst_xz(self) result(grid)
        class(karst_2d), intent(in) :: self
        real(sp), allocatable :: grid(:, :)
        real(sp), allocatable :: vol(:, :, :)

        call karst_volume(self%nx, 1, self%nz, vol, &
            n_passages=self%n_passages, n_ctrl=self%n_ctrl, &
            r_mean=self%r_mean, r_std=self%r_std, &
            tortuosity=self%tortuosity, p_connect=self%p_connect, &
            seed=self%seed, z_top=self%z_top)

        vol = permute(vol, 321)
        vol = flip(vol, [1])

        grid = vol(:, 1, :)

    end function generate_karst_xz

    !> Generate a full 3-D karst cave volume.
    !> Returns real(sp)(nz,ny,nx), top at index 1: 1.0 = cave void, 0.0 = host rock.
    function generate_karst_3d(self) result(vol)
        class(karst_3d), intent(in) :: self
        real(sp), allocatable :: vol(:, :, :)

        call karst_volume(self%nx, self%ny, self%nz, vol, &
            n_passages=self%n_passages, n_ctrl=self%n_ctrl, &
            r_mean=self%r_mean, r_std=self%r_std, &
            tortuosity=self%tortuosity, p_connect=self%p_connect, &
            seed=self%seed, z_top=self%z_top)

        vol = permute(vol, 321)
        vol = flip(vol, [1])

    end function generate_karst_3d

end module geological_model_karst
